// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzkiPCQ39ddADdinWxpST7z-uRDU5YYoY',
    appId: '1:1049327194877:web:aa688649cc12ce781d2494',
    messagingSenderId: '1049327194877',
    projectId: 'coffeenewdemo',
    authDomain: 'coffeenewdemo.firebaseapp.com',
    storageBucket: 'coffeenewdemo.firebasestorage.app',
    measurementId: 'G-KR574L7W9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGOBJvNpsifbCJSfzlmiCF932jsBm3Gx0',
    appId: '1:1049327194877:android:68824d76516cf3a81d2494',
    messagingSenderId: '1049327194877',
    projectId: 'coffeenewdemo',
    storageBucket: 'coffeenewdemo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXadHg4-SpJ7gtFZ1j53kewhqyDCuFWIA',
    appId: '1:1049327194877:ios:33e6e3a2d22dd9851d2494',
    messagingSenderId: '1049327194877',
    projectId: 'coffeenewdemo',
    storageBucket: 'coffeenewdemo.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShopDemo',
  );

}